###################################################################
#                                                                 #
#  This docker-compose.yaml file comprehends 1 profiles           #
#                                                                 #
#  - project:     Run backend with frontend                       #
#                                                                 #
#  To setup a specific profile, run:                              #
#  docker-compose --profile <profile> up -d                       #
#                                                                 #
#  More information at https://docs.docker.com/compose/profiles/  #
#                                                                 #
###################################################################

services:
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/app
    profiles:
      - project

  api:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/usr/src
    env_file:
      - "./backend/.env"
    profiles:
      - project