@startuml

package "Backend" {
  
  [FastAPI Service] --> [AnswerRouter]
   
  [AnswerRouter] --> [ChatService]
  [AnswerRouter] --> [ChatRepository]
  
  [ChatService] --> [AnswerTemplate]
  [ChatService] --> [ChatResponseHandler]

  [ChatRepository] --> [VectorDatabaseEnricher]
  
  [AnswerService] --> [OpenAILLM]

  [ContextEnricher] --> [Vector Database]
  [LLMAnswerer] --> [AI Model]
}

package "Adapters" {
  [AnswerDTO]
  [ChatDTO]
}

package "Core" {
  [RagChain]
}

package "Ports" {
  [RouterInterface] <|.. [Router]
}

[AnswerRouter] -|> [RouterInterface]

[ChatService] --> [RagChain]

@enduml